env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.28.0
    - RUST_NIGHTLY=nightly-2018-07-07
os:
  - linux
  - osx
language: rust
rust:
  - 1.31.1
sudo: false
branches:
  only:
    - master
    - stable
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt;
  - rustup component add clippy;
script:
  - set -x;
    cargo fmt -- --check &&
    cargo clippy &&
    cargo clippy --profile=test &&
    cargo test --release --verbose &&
    cargo test --verbose
before_cache:
  - cargo prune
